#!/bin/sh -l
set -eu

echo .NET Core Version: `sed -n 's|.*"version":\s*"\([^"]*\)".*|\1|p' src/global.json`
echo DOTNET_VERSION=`sed -n 's|.*"version":\s*"\([^"]*\)".*|\1|p' src/global.json` >> $GITHUB_ENV
