#!/bin/sh -l
set -eu

VERSION="${2-}"
[ -f "$1" ] && VERSION=$(sed -n 's|.*"version":\s*"\([^"]*\)".*|\1|p' "$1")

[ -z "$VERSION" ] && echo "Version not found" && exit 1

echo ".NET Version: $VERSION"
echo "DOTNET_VERSION=$VERSION" >> $GITHUB_ENV
echo "DOTNET_VERSION=$VERSION" >> $GITHUB_OUTPUT
